# Generated by Django 3.1.6 on 2021-02-16 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20210216_1412'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
