# Generated by Django 3.1.6 on 2021-02-17 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_message_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='person',
        ),
    ]
